carts/urls.py
from django.urls import path
from . import views
app_name= 'carts'
urlpatterns = [
    path('', views.cart, name='cart'),     
    path('agregar', views.add, name='add'),
    path('eliminar', views.remove, name='remove' )
    
]
 

products/urls.py
from django.urls import path
from . import views

app_name = 'products'
urlpatterns = [
     #pk es primary key la llave primaria
    path('search', views.ProductSearchListView.as_view(), name='search' ),
    path('<slug:slug>', views.ProductDetailView.as_view(), name='product' ),
    
]

store/urls.py
from xml.dom.minidom import Document
from django.contrib import admin
from django.urls import path
from django.urls import include
from products.views import ProductListView
from . import views
from django.conf.urls.static import static
from django.conf import settings

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('', views.index, name='index'),
    path('', ProductListView.as_view(), name='index'),
    path('usuarios/login', views.login_user, name='login'),
    path('usuarios/logout', views.logout_view, name='logout'),
    path('usuarios/register', views.register, name='register'),
    path('productos/', include('products.urls')),
    path('carrito/', include('carts.urls')),
    path('orden/', include('orders.urls')),
    path('direcciones/', include('shipping_addresses.urls')),
    path('codigos/', include('promo_codes.urls')),
    path('pagos/', include('billing_profiles.urls')),
] +static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/models.py
from django.db import models
from django.db.models.base import Model
from django.utils.text import slugify
from django.db.models.signals import pre_save
import uuid
# Create your models here.
class Product(models.Model):
    title = models.CharField(max_length=50)
    description = models.TextField()
    price = models.DecimalField(max_digits=8, decimal_places=2, default=0.0)
    slug = models.SlugField(null=False, blank=False, unique=True)
    image = models.ImageField(upload_to='products/' , null=False, blank= False)
    created_at = models.TimeField(auto_now_add=True)

    """
    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Product, self).save(*args, **kwargs)
    """
    def __str__(self):
        return self.title        

def set_slug(sender, instance, *args, **kwargs): # Debe recibir 5 elementos
    if instance.title and not instance.slug:
        slug = slugify(instance.title)

        
        # si existe algun producto con ese slug, genera uno nuevo
        while Product.objects.filter(slug=slug).exists():
            # pone caracteres aleatorios con la libreria uuid
            slug = slugify(
                '{}-{}'.format(instance.title, str(uuid.uuid4())[:8]  )
            )
        # La instancia es nuestro producto almacenado
        instance.slug = slug

# Antes que un objeto product se almacene, ejecuta el callback set_slug
pre_save.connect(set_slug, sender=Product)
    

products/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
from .models import Product
from django.views.generic.detail import DetailView
from django.db.models import Q #Ejecuta consulta aplicando diferentes filtros
# Create your views here.
class ProductListView(ListView):
    # Al importar de listview hay que definir 2 atributos
    template_name = 'index.html'
    # La consulta para obtener el listado de objetos
    queryset = Product.objects.all().order_by('-id')
 
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['message'] = 'Listado de productos'
        context['products'] = context['product_list']
        return context
        
class ProductDetailView(DetailView):
    # Obtiene un objeto y un registro mediante un identificador por default
    model = Product
    template_name = 'products/product.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        
        print(context)
        return context


class ProductSearchListView(ListView):
    template_name= 'products/search.html'
    
    def get_queryset(self):
        filters = Q(title__icontains=self.query()) | Q(category__title__icontains=self.query())
        # Realiza la consulta conteniendo alguna letra que se coloca en el buscador a partir de lo que nos envia el formulario en self.query
        return Product.objects.filter(filters)

    def query(self):        
        return self.request.GET.get('q')
        # Muestra el resultado en el template
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['query'] = self.query()
        context['count'] = context['product_list'].count()

        return context
        

products/templates/products/snippets/list.html
<div class="row">
    {% for object in product_list %}
        <div class="col-3 mt-5">
          {% include 'products/snippets/product.html' with product=object %}
        </div>
    {% endfor %}                    
  </div>

products/templates/products/snippets/product.html
<div class="card h-100">
    {% if product.image%}
      <img src="{{ product.image.url }} " alt="Imagen del producto">
    {% endif %}
    <div class="card-body">
      <h5 class="card-title">
        {{ product.title}}
      </h5>
      <p class="card-text">
        {{ product.description }}
      </p>
      <a href="{% url 'products:product' product.slug %} " class="btn btn-primary" >
        Ver mas
      </a>
    </div>
  </div>  

products/templates/products/snippets/search.html
<form action="{% url 'products:search' %} ">
    <div class="input-group">
        <!-- Se busca los producto con la q desde el queryset -->        
        <input class="form-control" type="text" name="q" value="{{ query }}" placeholder="Buscar">
        <div class="input-group-append">
            <input type="submit" value="Buscar" class="btn btn-primary" >
        </div>
    </div>
</form>

<!-- formulario con input nombre q que envia la informacion a travez del queryset por el metodo GET -->