billing_profiles/urls.py
from django.urls import path
from . import views

app_name = 'billing_profiles'

urlpatterns = [

    path('nuevo', views.create, name='create'),
]

carts/urls.py
from django.urls import path
from . import views
app_name= 'carts'
urlpatterns = [
    path('', views.cart, name='cart'),     
    path('agregar', views.add, name='add'),
    path('eliminar', views.remove, name='remove' )
    
]
 

orders/urls.py
from unicodedata import name
from django.urls import path
from . import views

app_name = 'orders'
urlpatterns = [
    path('', views.order, name='order'),
    path('direccion', views.address, name='address'),
    path('seleccionar/direccion', views.select_address, name='select_address'),
    path('establecer/direccion/<int:pk>', views.check_address, name='check_address'),
    path('confirmacion', views.confirm, name='confirm'),
    path('cancelar', views.cancel, name='cancel'),
    path('completar', views.complete, name='complete'),
    path('completados', views.OrderListView.as_view(), name='completeds'),

]

shipping_addresses/urls.py
from django.urls import path
from . import views

app_name = 'shipping_addresses'

urlpatterns = [
    path('', views.ShippingAddressListView.as_view(), name='shipping_addresses'),
    path('nuevo/', views.create, name='create'),
    path('editar/<int:pk>', views.ShippingAddressUpdateView.as_view(), name='update'),
    path('eliminar/<int:pk>', views.ShippingAddressDeleteView.as_view(), name='delete'),
    path('default/<int:pk>', views.default, name='default')

    
]

store/urls.py
from xml.dom.minidom import Document
from django.contrib import admin
from django.urls import path
from django.urls import include
from products.views import ProductListView
from . import views
from django.conf.urls.static import static
from django.conf import settings

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('', views.index, name='index'),
    path('', ProductListView.as_view(), name='index'),
    path('usuarios/login', views.login_user, name='login'),
    path('usuarios/logout', views.logout_view, name='logout'),
    path('usuarios/register', views.register, name='register'),
    path('productos/', include('products.urls')),
    path('carrito/', include('carts.urls')),
    path('orden/', include('orders.urls')),
    path('direcciones/', include('shipping_addresses.urls')),
    path('codigos/', include('promo_codes.urls')),
    path('pagos/', include('billing_profiles.urls')),
] +static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">    
    <title>Document</title>
    {% block css %}
    {% endblock %}
  </head>
  <body>

    {% include 'navbar.html' %}
    

    <div class="container">
      {% include 'messages.html' %}

      {% block breadcrumb %}
      {% endblock %}
      
    <div class="row mt-3">
      {% block content %}
      {% endblock %}
    </div>
   

    <!-- Footer -->
    <footer class="page-footer bg-dark font-small teal pt-4">
      <!-- Footer Text -->
      <div class="container text-center text-md-left">
        <!-- Grid row -->
        <div class="row" style="color: beige">
          <!-- Grid column -->
          <div class="col-md-6 mt-md-0 mt-3">
            <!-- Content -->
            <h5 class="text-uppercase font-weight-bold">Contacto</h5>

            <p>Ubicacion: Buenos aires, Argentina</p>
            <p>Numero Telefonico:</p>
            <p>011-2435-5654</p>
            <p>E-mail: distribuidora_mk@gmail.com</p>
          </div>
          <!-- Grid column -->

          <hr class="clearfix w-100 d-md-none pb-3" />

          <!-- Grid column -->
          <div class="col-md-6 mb-md-0 mb-3">
            <!-- Content -->
            <h5 class="text-uppercase font-weight-bold">Secciones:</h5>
            <p>Home</p>
            <p>Store</p>
            <p>Carrito</p>
            <p>Ayuda</p>
          </div>
          <!-- Grid column -->
        </div>
        <!-- Grid row -->
      </div>
      <!-- Footer Text -->

      <!-- Copyright -->
      <div class="footer-copyright text-center py-3" style="color: beige">
        © 2021 Copyright:
      </div>
      <!-- Copyright -->
    </footer>
    <!-- Footer -->
  </body>
  <script src="https://kit.fontawesome.com/e707059b7c.js" crossorigin="anonymous"></script>
  <script src="https://kit.fontawesome.com/7efd9e34c5.js"></script>

  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  {% block javascript %}
  {% endblock %}
</html>

templates/index.html
{% extends 'base.html' %}

{% block content %}
      
      <div class="col">        
      <h4 class="text-center">{{ message }}</h4>  
      {% include 'products/snippets/search.html' %}

      {% include 'products/snippets/list.html' %}
        
      
      <img
      src="https://marzin.com.ar/assets/uploads/files/dd6d4-5561b.jpg"
      alt=""
      class="rounded mx-auto d-block"
      style="height: 10"
    />
      </div>      
  

{% endblock %}

templates/messages.html
{% if messages %} 
        {% for message in messages %}
  
          <div class="alert {% if message.tags == 'success' %} alert-success {% else %} alert-danger {% endif %}">
            {{ message }}
          </div>  
        {% endfor %} 
      {% endif %}

templates/navbar.html
{% url 'register' as register %}
{% url 'login' as login %}
{% url 'logout' as logout %}
{% url 'carts:cart' as cart %}
{% url 'shipping_addresses:shipping_addresses' as shipping_addresses %}
{% url 'index' as index %}
{% url 'orders:completeds' as completeds %}
{% url 'billing_profiles:create' as billing_profiles %}

<nav class="navbar navbar-expand-md bg-dark navbar-dark">
     <a href="{{ index }} " class="navbar-brand"> Distribuidora MK </a>

    <button type="button" name="button" class="navbar-toggler navbar-toggler-right" data-toggle='collapse' data-target="#navb" >
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="navbar-collapse collapse hide" id="navb">
       
        <ul class="navbar-nav">
            <li class="nav-item {% if request.path == cart %}active{% endif %}">
                <a href="{{ cart }}"" class='nav-link' >Mi Carrito <span class="fas fa-shopping-cart"></span></a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item {% if request.path == shipping_addresses %}active{% endif %}">
                <a href="{{ shipping_addresses }}"" class='nav-link' >Mis Direcciones <span class="fas fa-location-arrow"></span></a>
            </li>
            <li class="nav-item {% if request.path == completeds %}active{% endif %}">
                <a href="{{ completeds }}"" class='nav-link' >Mis Pedidos <span class="fas fa-shopping-bag"></span></a>
            </li>
            <li class="nav-item {% if request.path == billing_profiles %}active{% endif %}">
                <a href="{{ billing_profiles }}"" class='nav-link' >Mis Metodos de Pago <span class="fas fa-money-check-alt"></span></a>
            </li>
            {% endif %}
        </ul>
        
        <ul class="nav navbar-nav ml-auto">
            {% if user.is_authenticated %}
                <li class="navbar-item">                
                    <a href="{% url 'logout' %} " class="nav-link" >
                        <i class="fas fa-sign-out-alt"></i>
                        Logout</a>
                </li>
            {% else %}
                <li class="navbar-item {% if request.path == login %} active {% endif %} ">
                    <a href="{% url 'login' %} " class="nav-link" >
                        <span class="fas fa-user"></span>
                        Login</a>
                </li>
                <li class="navbar-item {% if request.path == register %} active {% endif %}">
                    <a href="{{ register }} " class="nav-link" >
                        <span class="fas fa-user-plus"></span>
                        Registro</a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav> 

templates/navviejo.html
<!--
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
        <a class="navbar-brand" href="#">
            <img
            src="https://getbootstrap.com/docs/5.1/assets/brand/bootstrap-logo.svg"
            alt=""
            width="30"
            height="24"
            class="d-inline-block align-text-top"
            />
            Distribuidora MK
        </a>
        <button
            class="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent"
            aria-expanded="false"
            aria-label="Toggle navigation"
        >
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" href="#">Store</a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" href="#">Contacto</a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" href="#">Carrito</a>
            </li>
            </ul>
            
                <!--    
            <form class="d-flex">
            <input
                class="form-control me-2"
                type="search"
                placeholder="Search"
                aria-label="Search"
            />
            <button class="btn btn-outline-success" type="submit">
                Search
            </button>
            </form>
                -->
            </div>
            <div id="navb" class="navbar-collapse collapse hide pull-right">
                <ul class="nav navbar-nav ml-auto ">
                    <li class="navbar-item">
                        <a href="#">
                            Login
                        </a>
                    </li>
                </ul>
            </div>
            </div>
        </nav>
    -->